config/routes.rb
Rails.application.routes.draw do
  devise_for :drivers, path: 'driver'
  resources :drivers
  get '/drivers/:id/checkin', to: 'drivers#checkin' , as: :checkin
  post '/drivers/:id/save_checkin', to: 'drivers#save_checkin' , as: :save_checkin
  get '/drivers/:id/worked_hours', to: 'drivers#see_worked_hours' , as: :see_worked_hours

  root to: 'drivers#index'

  #resources :drivers do
  #  resources :check_ins
  #end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
    belongs_to :driver
end

app/models/driver.rb
class Driver < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
    has_many :check_ins #, dependent: :destroy

    def findCheckinsOfLastWeek
        today = Date.today
        lastWeekCheckins = []

        self.check_ins.each do |checkin| 
            if checkin.date < today-7      #it returns the array when it reachs a week before
                return lastWeekCheckins
            end
            lastWeekCheckins.append(checkin)
        end 
    end

    def calculateWorkedHoursOfLastWeek
        totalHours = 0
        checkins = findCheckinsOfLastWeek

        checkins.each do |checkin|
            totalHours += checkin.hours
        end   

        return totalHours
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_driver!
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy, :save_checkin, :checkin, :see_worked_hours]


  def checkin
    if current_driver != @driver 
      respond_to do |format|
        format.html { redirect_to @driver, notice: 'You can only check in for yourself' }
      end
    end
    
    #redirects to the html template in which the driver indicates the hours worked
  end 

  def save_checkin
    if @driver.check_ins.create(date: Date.today, hours: params[:hours]) 
      redirect_to drivers_path, notice: 'Checked-in.'
    else
      redirect_to drivers_path, notice: 'Something went wrong.'
    end
  end 

  def see_worked_hours
    @workedHours = @driver.calculateWorkedHoursOfLastWeek
   # directly from controller:  @workedHours = @driver.check_ins.where("date>=?", 7.days.ago).sum(:hours)

  end

  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
    if current_driver != @driver
      respond_to do |format|
        format.html { redirect_to @driver, notice: 'You can edit only your information ' }
      end
    end
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_driver.admin == true
      @driver.destroy
      respond_to do |format2|
        format2.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
        format2.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def driver_params
      params.require(:driver).permit(:name, :surname, :email, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
        <% driver.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/checkin.html.erb
<h3>Check in how many hours you worked today<h3>

<%= form_with(url: "/drivers/#{@driver.id}/save_checkin", method: "post") do %>
  <%= label_tag(:hours) %>
  <%= number_field_tag(:hours) %>
  <%= submit_tag("Check In") %>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>E-mail</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= driver.surname %></td>
        <td><%= driver.email %></td>
        <td><%= driver.city %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Check-in', checkin_path(driver) %></td>
        <td><%= link_to 'See Hours Worked', see_worked_hours_path(driver) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/see_worked_hours.html.erb
<h3>The driver worked <%= @workedHours %> hours this week<h3>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @driver.surname %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @driver.email %>
</p>

<p>
  <strong>City:</strong>
  <%= @driver.city %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DriverTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>